### ISSUE TITLE
demo or screenshot??

### ISSUE THREAD

**Issue by pomazanbohdan** [broadcastle/crm#1]
demo or screenshot??

**Comment by hcarriz** [comment]
I'll have a asciinema recording soon&trade;.

**Comment by hcarriz** [comment]
Here is a demo of what is functional so far.

[![asciicast](https://asciinema.org/a/QRCmPAI0fLj2B6ieMZ2Moijtd.png)](https://asciinema.org/a/QRCmPAI0fLj2B6ieMZ2Moijtd)
